// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS05QfPxpLDUgyVhQ_SYSFgK0_5CopOGo',
    appId: '1:393532845958:web:9048d7f0931c7b88b44607',
    messagingSenderId: '393532845958',
    projectId: 'fir-loginapp-f18e1',
    authDomain: 'fir-loginapp-f18e1.firebaseapp.com',
    storageBucket: 'fir-loginapp-f18e1.appspot.com',
    measurementId: 'G-MX8PP87HS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB490hBxh6FSBRobsVocwgs_p8DtcCYpP0',
    appId: '1:393532845958:android:35acdba6fb593ca7b44607',
    messagingSenderId: '393532845958',
    projectId: 'fir-loginapp-f18e1',
    storageBucket: 'fir-loginapp-f18e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJnuZiiXRDxyuKMj4cqzhDR5e1xwDq__Q',
    appId: '1:393532845958:ios:dbce6c922756f2d7b44607',
    messagingSenderId: '393532845958',
    projectId: 'fir-loginapp-f18e1',
    storageBucket: 'fir-loginapp-f18e1.appspot.com',
    iosBundleId: 'com.example.firebaseEmailAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJnuZiiXRDxyuKMj4cqzhDR5e1xwDq__Q',
    appId: '1:393532845958:ios:ddb86d39a9522fedb44607',
    messagingSenderId: '393532845958',
    projectId: 'fir-loginapp-f18e1',
    storageBucket: 'fir-loginapp-f18e1.appspot.com',
    iosBundleId: 'com.example.firebaseEmailAuth.RunnerTests',
  );
}
